export const FETCH_BACKGROUNDCOLOR_REQUEST = "FETCH_BACKGROUNDCOLOR_REQUEST";
export const FETCH_BACKGROUNDCOLOR_SUCCESS = "FETCH_BACKGROUNDCOLOR_SUCCESS";
export const FETCH_BACKGROUNDCOLOR_FAILED = "FETCH_BACKGROUNDCOLOR_FAILED";
export const FETCH_BACKGROUNDCOLOR = "FETCH_BACKGROUNDCOLOR";
export const SAVE_BACKGROUNDCOLOR = "SAVE_BACKGROUNDCOLOR";
export const SAVE_OPACITY = "SAVE_OPACITY";
export const FETCH_CLEAR_COLOR_MENU = "FETCH_CLEAR_COLOR_MENU";
