export const FETCH_UPDATE_BUTTON_REQUEST = "FETCH_UPDATE_BUTTON_REQUEST";
export const FETCH_UPDATE_BUTTON_VIEW = "FETCH_UPDATE_BUTTON_VIEW";
export const FETCH_UPDATE_BUTTON_ERROR = "FETCH_UPDATE_BUTTON_ERROR";
export const FETCH_UPDATE_BUTTON_UPDATE = "FETCH_UPDATE_BUTTON_UPDATE";
export const FETCH_UPDATE_BUTTON_CREATE = "FETCH_UPDATE_BUTTON_CREATE";
export const FETCH_CLEAR_UPDATE_BUTTON = "FETCH_CLEAR_UPDATE_BUTTON";
